/**
 * File and folder generation for `acr setup local`.
 *
 * Secrets (DATABASE_URL, EMBEDDING_API_KEY) go in `.env` only.
 * Non-secret config (project metadata, storage mode, provider/model) goes in `.acr/config.json`.
 */

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

// ─── Types ──────────────────────────────────────────────────────

export interface SetupConfigData {
  projectName: string;
  storageMode: string;
  embeddingProvider: string;
  embeddingModel: string;
}

export interface SetupEnvData {
  databaseUrl?: string;
  embeddingApiKey?: string;
  githubToken?: string;
}

// ─── Folder Tree ────────────────────────────────────────────────

const PROJECT_DIRS = ['sources', 'cache', 'exports', 'data'];

/**
 * Create the project folder tree.
 * Returns the list of created directories.
 */
export function createProjectTree(rootPath: string): string[] {
  const created: string[] = [];

  if (!existsSync(rootPath)) {
    mkdirSync(rootPath, { recursive: true });
    created.push(rootPath);
  }

  for (const dir of PROJECT_DIRS) {
    const dirPath = join(rootPath, dir);
    if (!existsSync(dirPath)) {
      mkdirSync(dirPath, { recursive: true });
      created.push(dirPath);
    }
  }

  // .acr directory
  const acrDir = join(rootPath, '.acr');
  if (!existsSync(acrDir)) {
    mkdirSync(acrDir, { recursive: true });
    created.push(acrDir);
  }

  return created;
}

// ─── Config File (.acr/config.json) ─────────────────────────────
// Non-secret project config only. No DATABASE_URL or API keys.

export function writeSetupConfig(rootPath: string, data: SetupConfigData): string {
  const acrDir = join(rootPath, '.acr');
  if (!existsSync(acrDir)) {
    mkdirSync(acrDir, { recursive: true });
  }

  const config = {
    project_name: data.projectName,
    storage_mode: data.storageMode,
    embedding_provider: data.embeddingProvider,
    embedding_model: data.embeddingModel,
  };

  const filePath = join(acrDir, 'config.json');
  writeFileSync(filePath, JSON.stringify(config, null, 2) + '\n');
  return filePath;
}

// ─── Env File (.env) ────────────────────────────────────────────
// Secrets and connection strings only.

export function writeSetupEnv(rootPath: string, data: SetupEnvData): string {
  const lines: string[] = [
    '# ─── ACR Environment ─────────────────────────────────────────',
    '# Generated by `acr setup local`',
    '',
    '# Database connection (Supabase, local Postgres, or any Postgres-compatible URL)',
    `DATABASE_URL=${data.databaseUrl ?? ''}`,
    '',
    '# Embedding provider API key (OpenAI recommended)',
    '# Get a key: https://platform.openai.com/api-keys',
    `EMBEDDING_API_KEY=${data.embeddingApiKey ?? ''}`,
    '',
    '# ─── Optional ───────────────────────────────────────────────',
    '# GitHub PAT — increases API rate limit from 60 to 5000 req/hr',
    '# Only needed for github_repo sources',
    `# GITHUB_TOKEN=${data.githubToken ?? ''}`,
    '',
  ];

  const filePath = join(rootPath, '.env');
  writeFileSync(filePath, lines.join('\n'));
  return filePath;
}

// ─── README ─────────────────────────────────────────────────────

export function writeSetupReadme(rootPath: string, projectName: string): string {
  const content = `# ${projectName}

Anchor workspace — agent-first context infrastructure.

## What's Here

| Path | Purpose |
|------|---------|
| \`.acr/config.json\` | Project configuration (storage mode, embedding settings) |
| \`.env\` | Secrets and connection strings (**do not commit**) |
| \`sources/\` | Local source files |
| \`cache/\` | Temporary sync cache |
| \`exports/\` | Exported data and snapshots |
| \`data/\` | Working data directory |

## Quick Start

\`\`\`bash
# Verify your setup
acr doctor

# Add a source
acr source add --name "MCP Docs" --type docs_site --url https://modelcontextprotocol.io/docs

# Sync all sources
acr sync --all

# Search your context
acr search "What is MCP?"
\`\`\`

## Re-run Setup

\`\`\`bash
acr setup local --path ${rootPath}
\`\`\`

## Learn More

- [Anchor README](https://github.com/mikestangdevs/anchor#readme)
- [Contributing Guide](https://github.com/mikestangdevs/anchor/blob/main/CONTRIBUTING.md)
`;

  const filePath = join(rootPath, 'README.md');
  writeFileSync(filePath, content);
  return filePath;
}

// ─── Helpers ────────────────────────────────────────────────────

/**
 * Get a sibling folder name (anchor-2, anchor-3, etc.)
 */
export function getSiblingPath(basePath: string): string {
  let attempt = 2;
  while (existsSync(`${basePath}-${attempt}`)) {
    attempt++;
  }
  return `${basePath}-${attempt}`;
}
